/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ALevelRouteImport } from './routes/a-level'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EntryTestPrepRouteImport } from './routes/entry-test-prep'
import { Route as ExamPreparationRouteImport } from './routes/exam-preparation'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as OLevelRouteImport } from './routes/o-level'
import { Route as StudentSupportRouteImport } from './routes/student-support'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ALevelRoute = ALevelRouteImport.update({
  id: '/a-level',
  path: '/a-level',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryTestPrepRoute = EntryTestPrepRouteImport.update({
  id: '/entry-test-prep',
  path: '/entry-test-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamPreparationRoute = ExamPreparationRouteImport.update({
  id: '/exam-preparation',
  path: '/exam-preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const OLevelRoute = OLevelRouteImport.update({
  id: '/o-level',
  path: '/o-level',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSupportRoute = StudentSupportRouteImport.update({
  id: '/student-support',
  path: '/student-support',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-level': typeof ALevelRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/entry-test-prep': typeof EntryTestPrepRoute
  '/exam-preparation': typeof ExamPreparationRoute
  '/faq': typeof FaqRoute
  '/methodology': typeof MethodologyRoute
  '/o-level': typeof OLevelRoute
  '/student-support': typeof StudentSupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-level': typeof ALevelRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/entry-test-prep': typeof EntryTestPrepRoute
  '/exam-preparation': typeof ExamPreparationRoute
  '/faq': typeof FaqRoute
  '/methodology': typeof MethodologyRoute
  '/o-level': typeof OLevelRoute
  '/student-support': typeof StudentSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-level': typeof ALevelRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/entry-test-prep': typeof EntryTestPrepRoute
  '/exam-preparation': typeof ExamPreparationRoute
  '/faq': typeof FaqRoute
  '/methodology': typeof MethodologyRoute
  '/o-level': typeof OLevelRoute
  '/student-support': typeof StudentSupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-level'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/entry-test-prep'
    | '/exam-preparation'
    | '/faq'
    | '/methodology'
    | '/o-level'
    | '/student-support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-level'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/entry-test-prep'
    | '/exam-preparation'
    | '/faq'
    | '/methodology'
    | '/o-level'
    | '/student-support'
  id:
    | '__root__'
    | '/'
    | '/a-level'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/entry-test-prep'
    | '/exam-preparation'
    | '/faq'
    | '/methodology'
    | '/o-level'
    | '/student-support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ALevelRoute: typeof ALevelRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  EntryTestPrepRoute: typeof EntryTestPrepRoute
  ExamPreparationRoute: typeof ExamPreparationRoute
  FaqRoute: typeof FaqRoute
  MethodologyRoute: typeof MethodologyRoute
  OLevelRoute: typeof OLevelRoute
  StudentSupportRoute: typeof StudentSupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-level': {
      id: '/a-level'
      path: '/a-level'
      fullPath: '/a-level'
      preLoaderRoute: typeof ALevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry-test-prep': {
      id: '/entry-test-prep'
      path: '/entry-test-prep'
      fullPath: '/entry-test-prep'
      preLoaderRoute: typeof EntryTestPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-preparation': {
      id: '/exam-preparation'
      path: '/exam-preparation'
      fullPath: '/exam-preparation'
      preLoaderRoute: typeof ExamPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-level': {
      id: '/o-level'
      path: '/o-level'
      fullPath: '/o-level'
      preLoaderRoute: typeof OLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-support': {
      id: '/student-support'
      path: '/student-support'
      fullPath: '/student-support'
      preLoaderRoute: typeof StudentSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ALevelRoute: ALevelRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  EntryTestPrepRoute: EntryTestPrepRoute,
  ExamPreparationRoute: ExamPreparationRoute,
  FaqRoute: FaqRoute,
  MethodologyRoute: MethodologyRoute,
  OLevelRoute: OLevelRoute,
  StudentSupportRoute: StudentSupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
